# Generated by Django 4.2.4 on 2023-09-03 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_delete_testablofazal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workcv',
            name='images',
            field=models.ImageField(upload_to='work/'),
        ),
    ]
